// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// axR_serial_open_cpp
SEXP axR_serial_open_cpp(std::string port, int baud);
RcppExport SEXP _axR_axR_serial_open_cpp(SEXP portSEXP, SEXP baudSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type port(portSEXP);
    Rcpp::traits::input_parameter< int >::type baud(baudSEXP);
    rcpp_result_gen = Rcpp::wrap(axR_serial_open_cpp(port, baud));
    return rcpp_result_gen;
END_RCPP
}
// axR_serial_close_cpp
void axR_serial_close_cpp(SEXP handle);
RcppExport SEXP _axR_axR_serial_close_cpp(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    axR_serial_close_cpp(handle);
    return R_NilValue;
END_RCPP
}
// axR_serial_write_cmd_cpp
std::string axR_serial_write_cmd_cpp(SEXP handle, std::string command, int timeout_ms);
RcppExport SEXP _axR_axR_serial_write_cmd_cpp(SEXP handleSEXP, SEXP commandSEXP, SEXP timeout_msSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    Rcpp::traits::input_parameter< std::string >::type command(commandSEXP);
    Rcpp::traits::input_parameter< int >::type timeout_ms(timeout_msSEXP);
    rcpp_result_gen = Rcpp::wrap(axR_serial_write_cmd_cpp(handle, command, timeout_ms));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_axR_axR_serial_open_cpp", (DL_FUNC) &_axR_axR_serial_open_cpp, 2},
    {"_axR_axR_serial_close_cpp", (DL_FUNC) &_axR_axR_serial_close_cpp, 1},
    {"_axR_axR_serial_write_cmd_cpp", (DL_FUNC) &_axR_axR_serial_write_cmd_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_axR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
