# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

axR_serial_open_cpp <- function(port, baud) {
    .Call('_axR_axR_serial_open_cpp', PACKAGE = 'axR', port, baud)
}

axR_serial_close_cpp <- function(handle) {
    invisible(.Call('_axR_axR_serial_close_cpp', PACKAGE = 'axR', handle))
}

axR_serial_write_cmd_cpp <- function(handle, command) {
    .Call('_axR_axR_serial_write_cmd_cpp', PACKAGE = 'axR', handle, command)
}

