# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

axR_omapi_startup_cpp <- function() {
    .Call(`_axR_axR_omapi_startup_cpp`)
}

axR_omapi_shutdown_cpp <- function() {
    .Call(`_axR_axR_omapi_shutdown_cpp`)
}

axR_omapi_error_string_cpp <- function(status) {
    .Call(`_axR_axR_omapi_error_string_cpp`, status)
}

axR_omapi_get_device_ids_cpp <- function() {
    .Call(`_axR_axR_omapi_get_device_ids_cpp`)
}

axR_omapi_get_device_info_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_get_device_info_cpp`, deviceId)
}

axR_omapi_get_battery_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_get_battery_cpp`, deviceId)
}

axR_omapi_self_test_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_self_test_cpp`, deviceId)
}

axR_omapi_get_memory_health_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_get_memory_health_cpp`, deviceId)
}

axR_omapi_get_accelerometer_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_get_accelerometer_cpp`, deviceId)
}

axR_omapi_get_time_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_get_time_cpp`, deviceId)
}

axR_omapi_set_time_cpp <- function(deviceId, year, month, day, hour, min, sec) {
    .Call(`_axR_axR_omapi_set_time_cpp`, deviceId, year, month, day, hour, min, sec)
}

axR_omapi_set_led_cpp <- function(deviceId, ledState) {
    .Call(`_axR_axR_omapi_set_led_cpp`, deviceId, ledState)
}

axR_omapi_is_locked_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_is_locked_cpp`, deviceId)
}

axR_omapi_set_lock_cpp <- function(deviceId, code) {
    .Call(`_axR_axR_omapi_set_lock_cpp`, deviceId, code)
}

axR_omapi_unlock_cpp <- function(deviceId, code) {
    .Call(`_axR_axR_omapi_unlock_cpp`, deviceId, code)
}

axR_omapi_get_ecc_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_get_ecc_cpp`, deviceId)
}

axR_omapi_set_ecc_cpp <- function(deviceId, enabled) {
    .Call(`_axR_axR_omapi_set_ecc_cpp`, deviceId, enabled)
}

axR_omapi_command_cpp <- function(deviceId, command, expected, timeoutMs) {
    .Call(`_axR_axR_omapi_command_cpp`, deviceId, command, expected, timeoutMs)
}

axR_omapi_get_delays_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_get_delays_cpp`, deviceId)
}

axR_omapi_set_delays_cpp <- function(deviceId, startZero, startInfinite, startYear, startMonth, startDay, startHour, startMin, startSec, stopZero, stopInfinite, stopYear, stopMonth, stopDay, stopHour, stopMin, stopSec) {
    .Call(`_axR_axR_omapi_set_delays_cpp`, deviceId, startZero, startInfinite, startYear, startMonth, startDay, startHour, startMin, startSec, stopZero, stopInfinite, stopYear, stopMonth, stopDay, stopHour, stopMin, stopSec)
}

axR_omapi_get_session_id_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_get_session_id_cpp`, deviceId)
}

axR_omapi_set_session_id_cpp <- function(deviceId, sessionId) {
    .Call(`_axR_axR_omapi_set_session_id_cpp`, deviceId, sessionId)
}

axR_omapi_get_metadata_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_get_metadata_cpp`, deviceId)
}

axR_omapi_set_metadata_cpp <- function(deviceId, metadata) {
    .Call(`_axR_axR_omapi_set_metadata_cpp`, deviceId, metadata)
}

axR_omapi_get_accel_config_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_get_accel_config_cpp`, deviceId)
}

axR_omapi_set_accel_config_cpp <- function(deviceId, rate, range) {
    .Call(`_axR_axR_omapi_set_accel_config_cpp`, deviceId, rate, range)
}

axR_omapi_erase_and_commit_cpp <- function(deviceId, eraseLevel) {
    .Call(`_axR_axR_omapi_erase_and_commit_cpp`, deviceId, eraseLevel)
}

axR_omapi_get_data_info_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_get_data_info_cpp`, deviceId)
}

axR_omapi_begin_downloading_cpp <- function(deviceId, offsetBlocks, lengthBlocks, destFile) {
    .Call(`_axR_axR_omapi_begin_downloading_cpp`, deviceId, offsetBlocks, lengthBlocks, destFile)
}

axR_omapi_query_download_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_query_download_cpp`, deviceId)
}

axR_omapi_wait_download_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_wait_download_cpp`, deviceId)
}

axR_omapi_cancel_download_cpp <- function(deviceId) {
    .Call(`_axR_axR_omapi_cancel_download_cpp`, deviceId)
}

